[project]
name = "pyxel_pacl"
version = "0.1.0a1"
authors = [
    {name = "Chiba-Tech", email = "saposoudan@chiba-th.ed.jp"},
]
dependencies = [
    "pyxel>=1.9.18",
    "wasmsockets>=0.1.4",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "BSD-4-Clause"}
